---
- name: "Copying .bashrc to home"
  copy:
    src: "{{ playbook_dir }}/roles/configure-bash/files/.bashrc"
    dest: "~/.bashrc"
- name: "Copying .bashrc Config to Root Directory"
  copy:
    src: "{{ playbook_dir }}/roles/configure-bash/files/.bashrcroot"
    dest: "/root/.bashrc"
  become: true
