---
- name: "Customizing OS"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/system-configs"
    - role: "roles/tools"
    - role: gantsign.visual-studio-code
    - role: "roles/logging-ufw"
    - role: "roles/firefox-custom"
    - role: "roles/configure-bash"
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - bmewburn.vscode-intelephense-client
            - ms-python.python
            - ms-python.vscode-pylance
            - leizongmin.node-module-intellisense
            - snyk-security.snyk-vulnerability-scanner
            - redhat.java
            - dgileadi.java-decompiler

