---
- name: "Copying repo to /tmp"
  command: "cp -r kali-clean/ /tmp/"
  args:
    chdir: "{{ playbook_dir }}/roles/kali-clean/files/"
  become: true
- name: "Installing Kali-Clean"
  shell: |
    cd /tmp/kali-clean
    ./install.sh
